name: CI Build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - uses: actions/checkout@v3
    - name: Build with dotnet
      run: dotnet build
